### ISSUE TITLE
Incorrect labels getting uploaded

### ISSUE THREAD

**Issue by planemad** [amishas157/wikidataLabelUpload#16]
<img width="910" alt="screenshot 2016-12-16 01 08 07" src="https://cloud.githubusercontent.com/assets/126868/21239297/464fdbde-c32c-11e6-92e2-4b8e33cefadd.png">

cc @amishas157

**Comment by planemad** [comment]
<img width="1115" alt="screenshot 2016-12-16 01 12 28" src="https://cloud.githubusercontent.com/assets/126868/21239402/c3a751b6-c32c-11e6-82d2-d10fc3f04ca3.png">

The label for Batuan Temple was uploaded to the item for Bali museum

**Comment by planemad** [comment]
Have reverted my edits

**Comment by amishas157** [comment]
@planemad 

Wanted to check the steps / commands you took to upload these translations

**Comment by amishas157** [comment]
@planemad 

Sorry, It was my bad. There was a case where it was not able to properly match to null `osm:wikidata` / `wiki:wikidata`. And that caused this issue.
Now it is fixed and good to go. Closing the issue
