### ISSUE TITLE
Alias gets uploaded even when it matches the label

### ISSUE THREAD

**Issue by planemad** [amishas157/wikidataLabelUpload#18]
Sometimes an alias is uploaded which is an exact duplicate of the existing label. It seems like some check is failing for some reason.

- అరౌకా డిపార్ట్మెంట్ https://www.wikidata.org/w/index.php?title=Q230223&diff=prev&oldid=469069625
- చారెంట్ https://www.wikidata.org/w/index.php?title=Q3266&diff=prev&oldid=469071885
- కోర్సె కౌంటీ https://www.wikidata.org/w/index.php?title=Q193464&diff=prev&oldid=469072504

**Comment by planemad** [comment]
@amishas157 logs for Hatay:

`{"properties:wikidata": "Q83274", "wiki:logs": "No te label,", "Name": "Hatay", "admin": "region", "Link to update Wikidata": "https://www.wikidata.org/wiki/Special:SetLabelDescriptionAliases/Q83274/te", "Wikidata Link": "https://wikidata.org/wiki/Q83274", "null": [""], "wiki:label:te": "\u0c39\u0c1f\u0c3e\u0c2f\u0c4d ", "logs": "Appending an alias"}`

**Comment by planemad** [comment]
The previous time I tried to upload, the te label for [Hatay](https://www.wikidata.org/w/index.php?title=Q83274&diff=prev&oldid=469076094) was already `హటాయ్` and the script added this as an alias.

On the current run, the log reports `Appending an alias`, but nothing actually got uploaded.

Result is that the place has both the label and alias exactly the same.

<img width="931" alt="screen shot 2017-03-31 at 7 24 36 pm" src="https://cloud.githubusercontent.com/assets/126868/24553390/c26e088a-1647-11e7-8ea0-96ba38e633be.png">

**Comment by amishas157** [comment]
@planemad 
Not really able to reproduce this issue on my system. It gives correct logs. But from logs you have shared, seems like this some pywikibot blip. So the probable case which would have happened is, pywikibot was not able to fetch existing `te` label / alias and based on this , it added new translation. The only thing which I can think of right now is try installing pywikibot again and then try it. Lets see if the issue still persists.

**Comment by planemad** [comment]
@amishas157 can you try uploading with this test file:

```
Name,properties:wikidata,admin,wiki:logs,Wikidata Link,wiki:label:te,Link to update Wikidata,Priority
Hatay,Q83274,region,"No te label,",https://wikidata.org/wiki/Q83274,హటాయ్ ,https://www.wikidata.org/wiki/Special:SetLabelDescriptionAliases/Q83274/te,
```

**Comment by amishas157** [comment]
@planemad , Sorry this was coming as the translation name was present with a space, `హటాయ్ `. It was comparing `హటాయ్ ` and `హటాయ్`. Fixed the issue by trimming the spaces around the actual value. Thanks for flagging.

**Comment by planemad** [comment]
👍 works!
