### ISSUE TITLE
Pywikibot

### ISSUE THREAD

**Issue by 1ec5** [amishas157/wikidataLabelUpload#6]
Please consider rewriting this and future bots based on [pywikibot](https://www.mediawiki.org/wiki/Manual:Pywikibot), a well-established, object-oriented framework for writing MediaWiki bots. The vast majority of bots on Wikimedia sites are written using this framework (including my own). In addition to [built-in Wikidata support](https://www.mediawiki.org/wiki/Manual:Pywikibot/Wikidata), pywikibot has sophisticated logic for avoiding rate limiting (#5), handling a wide variety of API responses (#4), and OAuth or bot password authentication (#3). That way you can focus on the fun parts of being a botmaster! 😄

/cc @amishas157 @planemad

**Comment by amishas157** [comment]
Thanks @1ec5 . It worked and solved all other issues. :)

**Comment by 1ec5** [comment]
Yay!
